
SELECT
    ac.table_name,
    acc.column_name,ac.owner
FROM
    all_constraints ac
JOIN
    all_cons_columns acc
ON
    ac.constraint_name = acc.constraint_name
AND
    ac.owner = acc.owner
WHERE
    ac.constraint_type = 'P'
AND
    ac.owner = 'PLF'
AND AC.table_name IN ( 'ASSET_MAKE',
'ASSET_MODEL',
'CASHDEPOSITS',
'COLLATERAL_VEHICLE_ED',
'COLLATERALASSIGNMENT',
'CUSTOMER_CORP_ED',
'CUSTOMER_RETAIL_ED',
'CUSTOMERPHONENUMBERS',
'CUSTOMERS',
'DEALER',
'DEPOSITMOVEMENTS',
'ENTITY',
'FEETYPES',
'FINADVANCEPAYMENTS',
'FINANCEMAIN',
'FINDISBURSEMENTDETAILS',
'FINEXCESSAMOUNT',
'FINFEEDETAIL',
'FINJOINTACCOUNTDETAILS',
'FINLOGENTRYDETAIL',
'FINODDETAILS',
'FINPFTDETAILS',
'FINRECEIPTDETAIL',
'FINRECEIPTHEADER',
'FINSCHEDULEDETAILS',
'FINSCHEDULEDETAILS_LOG',
'FINWRITEOFFDETAIL',
'FINWRITEOFFPAYMENT',
'JVPOSTINGS',
'LOAN_AL_ORG_ED',
'MANDATES',
'MANUALADVISE',
'PAYMENTDETAILS',
'PAYMENTHEADER',
'PAYMENTINSTRUCTIONS',
'POSTINGS',
'PROMOTIONS',
'RECEIPTALLOCATIONDETAIL',
'REPOSSESSION_LOAN_REQ',
'RMTBRANCHES',
'RMTCURRENCIES',
'RMTCUSTTYPES',
'RMTFINANCETYPES',
'SMTDIVISIONDETAIL',
'SMTPARAMETERS',
'RMTCOUNTRYVSPROVINCE')